### ISSUE TITLE
detailed description

### ISSUE THREAD

**Issue by LLL06250901** [HPLQAQ/SAM-Deblur#3]
Hello, thank you very much for your contribution. When will the detailed description be released？

**Comment by HPLQAQ** [comment]
Thanks for your interest!
The core implementation of our method is at https://github.com/HPLQAQ/SAM-Deblur/blob/main/basicsr/models/archs/SegNAFNet_arch.py . 
Detailed description and config files will be updated after paper acceptance result in a week.

**Comment by HPLQAQ** [comment]
Thanks again for your interest! Our paper has just been accepted to ICASSP 2024.
Detailed description has been released.
Now you can start an experiment easily following instructions in [README](https://github.com/HPLQAQ/SAM-Deblur).
Also, welcome visit our [project page](https://hplqaq.github.io/projects/sam-deblur) for a quick overview of the paper.
