### ISSUE TITLE
代码跑不起来

### ISSUE THREAD

**Issue by Xingshi-tech** [HPLQAQ/SAM-Deblur#6]
试了下，给了test.py但是提供的数据集又少了masks？跑训练代码也是各种问题，真的除了作者有人能把这个代码跑通吗？

**Comment by HPLQAQ** [comment]
提供的数据中有grouped_masks文件。
Download prepared data for experiments from [Baidu Netdisk](https://pan.baidu.com/s/1jHgwKqFuyyy8yixByiEfCg?pwd=hplv)|[Onedrive](https://1drv.ms/f/s!Ar-cR-XYHDTtgt8pYy2MBqQvroXl-Q?e=U7o4xc).  
代码在完全没有进行过相关实验的GPU服务器上使用conda配置描述中的环境
```
python 3.10.13
pytorch 1.13.1
```
并严格按照描述流程完成了完整的复现。
代码基于被广泛使用的BasicSR库，修改仅一小部分，您可以先尝试运行NAFNet或BasicSR看是否能正常运行。

发issue时请遵循github的礼仪，您可以提供您运行时遇到的error信息，我在有空情况下可以尝试协助解决。

同时向其他暂未回复的issue和邮件道歉，本人确实在短期内没有余力维护该项目，问题主要集中在数据集以及预处理部分，该部分代码均已提供并说明，但未整理（只整理代码很简单，但还需要在新的可用服务器上迁移数据集确保可复现），可参照论文中作为baseline的Zheyan Jin, Shiqi Chen, Yueting Chen, Zhihai Xu, and
Huajun Feng, “Let segment anything help image dehaze,”
arXiv preprint arXiv:2306.15870, 2023.中的伪代码描述。

**Comment by Xingshi-tech** [comment]
首先，十分感谢作者回复并为我之前因为一晚上没能跑通代码而写下有些气愤的问题向作者表达歉意。其次，我看到1月份就有人说缺少masks的问题，但是到7月份我看Quick Start操作，发现所提供的REDs_val.zip下载包中依旧缺少masks，GoPro倒是提供了masks，但是运行的时候就报别的错了。
![image](https://github.com/HPLQAQ/SAM-Deblur/assets/72507096/e9ea21cf-1834-49c5-8301-bc1720a1bc61)

![image](https://github.com/HPLQAQ/SAM-Deblur/assets/72507096/e755e7bc-2ee9-4ae5-8b86-5e29dca3d5a2)

![image](https://github.com/HPLQAQ/SAM-Deblur/assets/72507096/ae993551-9b79-4391-ab8b-5757194063f4)

**Comment by HPLQAQ** [comment]
非常抱歉，可能我打包上传的压缩包会有一些问题，我会检查一下明天之内回复您，同时感谢您对我们工作的关注。
代码应该不会有问题，代码我是在全新环境完成复现之后直接通过git上传的。

**Comment by HPLQAQ** [comment]
您好，请确保您下载了REDS_val.z01并放在同一目录下解压，我复现了您的问题。
单独解压REDS_val.zip时出现以下情况：
![image](https://github.com/HPLQAQ/SAM-Deblur/assets/82659517/abe5fd28-b6b9-4599-8494-8422e08d39ec)
将REDS_val.z01放在同一目录下解压时可以正常解压：
![image](https://github.com/HPLQAQ/SAM-Deblur/assets/82659517/fb3d690b-43d4-425f-b030-83d2a82a181f)
我使用的压缩软件是Bandizip，同时我测试了使用7zip可以正常解压：
![image](https://github.com/HPLQAQ/SAM-Deblur/assets/82659517/e04e7537-4f16-437f-a4c1-e95946d3d7f5)
请确保你下载了分卷压缩文件并使用了可以识别分卷的压缩软件，我猜测您的训练无法正常运行可能也是因为解压的数据不全导致的。

**Comment by HPLQAQ** [comment]
同时我会尽快补充上可以直接集成SAM运行的代码，这么做可以解决当前所有issue的共有问题。

**Comment by Xingshi-tech** [comment]
好嘞，辛苦啦
